# PROJECT 1 MACHINE LEARNING

In [7]:
from implementations import *
from helpers import *
import matplotlib.pyplot as plt
import numpy as np

## Loading data

In [4]:
x_train, x_test, y_train, train_ids, test_ids = load_csv_data('dataset/data/', sub_sample=False)

In [91]:
print('Shapes of x_train :', x_train.shape)
print('Shapes of y_train :', y_train.shape)
print('Shapes of x_test :', x_test.shape)

Shapes of x_train : (328135, 321)
Shapes of y_train : (328135,)
Shapes of x_test : (109379, 321)


In [61]:
def standardize(x):
    """Standardize the original data set."""
    mean_x = np.mean(x, axis=0)
    x = x - mean_x
    std_x = np.std(x, axis=0)
    x = x / std_x
    return x, mean_x, std_x

### Preparation of data : nan -> 0, standardization

In [70]:
x_train_cleaned = np.nan_to_num(x_train, nan=0.0)
print(x_train_cleaned.shape)
x_train_final,_,_ = standardize(x_train_cleaned)
print(x_train_final.shape)

(328135, 321)
(328135, 321)


### Computation of initial w, and then algo of logistic regression

In [98]:
#Using linalg.pinv because x_train_cleaned is a singular matrix so no inverse
w = np.linalg.pinv(x_train_final.T.dot(x_train_final)).dot(x_train_final.T.dot(y_train))

In [97]:
nb_steps = 20
gamma = 0.001

for i in range(nb_steps):
    loss, w = logistic_regression(y_train, x_train_cleaned, w, gamma)

### Computation of the y predicted with the x_test and 

In [86]:
x_test_cleaned = np.nan_to_num(x_train, nan=0.0)
x_test_final,_,_ = standardize(x_test_cleaned)
x = np.dot(x_test_final, w)
y_pred_proba = sigmoid (np.dot(x_test_final, w))
print(y_pred_proba)

[0. 1. 0. ... 1. 1. 1.]


In [88]:
threshold = 0.5
y_pred = (y_pred_proba >= threshold).astype(int)
print(y_pred)

[0 1 0 ... 1 1 1]


In [89]:
y_pred[y_pred == 0] = -1
print(y_pred)

[-1  1 -1 ...  1  1  1]


In [93]:
name = 'sample-submission.csv '
create_csv_submission(test_ids, y_pred, name)